### PR TITLE
Correct the use iau_offset and add new functions to output restart files

### PR DESCRIPTION
**Pull request by MingjingTong-NOAA**
This PR is part of the changes made to enable DA cycling functions. In particular, the use of iau_offset variable has been corrected and new functions to control the output of restart files has been added, which allows the output of the restart file at the first time step through the control parameter restart_first_time_step and a new parameter restart_start is used to specify the starting time to output the restart file.  

A forecast test was run to compare with the main branch and the results are bit-wise identical.

### CODE REVIEW

**Comment by MingjingTong-NOAA** [comment]
@JosephMouallem and @laurenchilutti, I couldn't assign the reviewers of this PR from the github page. This PR is one of the four PRs for shield DA related changes. Other three PRs are listed below

https://github.com/NOAA-GFDL/SHiELD_physics/pull/81
https://github.com/NOAA-GFDL/atmos_drivers/pull/70
https://github.com/NOAA-GFDL/SHiELD_build/pull/79

The above failing check can be resolved by including the changes in https://github.com/NOAA-GFDL/atmos_drivers/pull/70

The test case and scripts can be found in this google doc: https://docs.google.com/document/d/1gWwZoDWtxfpDuKmH99oeBUzgGe_pmdGZb8N1P8fxy_0/edit?tab=t.0

Thank you for reviewing the code.

File: full/full_coupler_mod.F90 [hunk 1]
```diff
@@ -908,6 +917,7 @@ subroutine coupler_init(Atm, Ocean, Land, Ice, Ocean_state, Atmos_land_boundary,
         endif
 
         call fms_mpp_clock_begin(coupler_clocks%atmos_model_init)
+        Atm%iau_offset = iau_offset
```
Comment (laurenchilutti) [inline full/full_coupler_mod.F90]: This is causing the CI testing to fail on this PR with the compilation error: "Error: 'iau_offset' at (1) is not a member of the 'atmos_data_type' structure"

**Comment by laurenchilutti** [comment]
It is important for this PR to be reviewed for compatibility with other GFDL models.  The PRs in FMS Coupler are now going to be reviewed by the fmscoupler task force.  The email for this group is: <oar.gfdl.fmscoupler-task-force@noaa.gov>.  We should schedule a meeting to present these changes and seek their input.

**Comment by JosephMouallem** [comment]
@MingjingTong-NOAA: While all models now run with the full coupler, unlike SHiELD, the other models use a different atmosphere driver `atmos_drivers/coupled/atmos_model.F90`.

The failed check occurs because the tests here run under this configuration `atmos_drivers/coupled/atmos_model.F90` rather than `atmos_drivers/SHiELD/atmos_model.F90`.  Since `iau_offset` is not present in the `atmos_data_type` in `atmos_drivers/coupled/atmos_model.F90`, the compilation fails.

**Comment by lharris4** [comment]
Is it possible to put these modifications into `atmos_drivers/SHiELD/atmos_model.F90`, so they remain specific to SHiELD?

**Comment by MingjingTong-NOAA** [comment]
Hi All,

Thank you so much for reviewing the PRs. I'll address all your comments in the coming couple of days.

**Comment by MingjingTong-NOAA** [comment]
I've moved the iau_offset related changes into atmos_drivers/SHiELD/atmos_model.F90

**Review by uramirez8707 — APPROVED** [review]

**Comment by JosephMouallem** [comment]
As per our last discussion, the changes here will be moved to the atmosphere driver level, so no changes will be made here, thanks.

**Comment by laurenchilutti** [comment]
@MingjingTong-NOAA Can you confirm: were the changes here moved to the atmos_drivers level? Can this PR be closed?

**Comment by MingjingTong-NOAA** [comment]
@laurenchilutti The iau_offset variable was moved from full_coupler_mod.F90 to atmos_drivers/SHiELD/atmos_model.F90. No changes need to be made in this repo. The PR can be closed.

**Comment by laurenchilutti** [comment]
Thank you, closing this.
